### ISSUE TITLE
cuda 11.0  is not supported?

### ISSUE THREAD

**Issue by henbucuoshanghai** [AllentDan/LibtorchTutorials#13]
I  download libtorch,and unzip it .

libtorch/include/c10/cuda/CUDAStream.h:6:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include <cuda_runtime_api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

why,tks

**Comment by AllentDan** [comment]
Please ensure your CUDA toolkit is installed and the environment variable is set.
