### ISSUE TITLE
加载模型时存在的问题

### ISSUE THREAD

**Issue by for-just-we** [AllentDan/LibtorchTutorials#15]
你好，我最近参考你的代码加载模型时碰到了点问题

教程[第五章](https://allentdan.github.io/2021/01/18/libtorch%E6%95%99%E7%A8%8B%EF%BC%88%E4%BA%94%EF%BC%89/)，给出了用pytorch保存模型时用 

```python
traced_script_module = torch.jit.trace(model, var)
traced_script_module.save("vgg16bn.pt")
```

然后C++ libtorch加载模型时用 `torch::load(vgg16bn,"your path to vgg16bn.pt");`。

我用同样的python代码保存模型，加载模型用 `torch::load` 时报错：`In template: invalid operands to binary expression ('serialize::InputArchive' and '<ModelName>')`，但是用 `torch::jit::script::Module module = torch::jit::load(modelPath);` 可以加载模型。

我想问下前一个错误能怎么解决呢？虽然第二种方式可以加载模型但是是黑箱方式加载，我还是希望能用白盒方式加载模型。

我用的pytorch和libtorch是1.4.0版本

**Comment by AllentDan** [comment]
文档里写了可能的原因：

模型保存错了，无法正确加载
路径不对，没正确指向（可能非常大）
c++中定义的模型和python中定义的不一致，最好打印下来，复制到文件中对比文档。

**Comment by for-just-we** [comment]
> 文档里写了可能的原因：
> 
> 模型保存错了，无法正确加载 路径不对，没正确指向（可能非常大） c++中定义的模型和python中定义的不一致，最好打印下来，复制到文件中对比文档。

但是 `torch::load` 报错不是运行错误，是编译错误。然后c++其实是可以加载模型的，只是我想用 `torch::load` 进行白盒加载，因为 `torch::jit::load` 是黑盒模式的加载。如果只是模型路径问题或者保存问题的话编译应该是没问题的吧

**Comment by AllentDan** [comment]
第三条，要求模型完全一致，即使名字一致也要注意各层参数是否一样

**Comment by for-just-we** [comment]
> 要求模型完全一致

这个都是一样的

**Comment by AllentDan** [comment]
那就不知道了，建议先试个最简单的模型，一个bn层这种，再二分查找问题点，

**Comment by erzhu222** [comment]
> > 要求模型完全一致
> 
> 这个都是一样的

请问问题解决了吗
