### ISSUE TITLE
CMake引入libtorch存在的一个问题

### ISSUE THREAD

**Issue by for-just-we** [AllentDan/LibtorchTutorials#16]
作者你好，我按照官网 `-DCMAKE_PREFIX_PATH=<path2libtorch> ..` 引入libtorch库，然后cmake的时候报出以下警告

```bash
CMake Warning (dev) at xxx/cmake-3.20.0/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (torch) does
  not match the name of the calling package (Torch).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
```

然后我打印 `${TORCH_LIBRIRES}` 的值，是 `torch;torch_library;<path2libtorch>/lib/libc10.so`。请问这个情况正常吗？我目前写个简单libtorch应用没问题，但是想将libtorch引入到klee时总是编译错误，链接不到libtorch，不知道是不是跟这个有关。

**Comment by AllentDan** [comment]
哪个官网？`klee`没用过

**Comment by for-just-we** [comment]
> 哪个官网？`klee`没用过

就是[这个](https://pytorch.org/tutorials/advanced/cpp_frontend.html#writing-a-basic-application)，我一开始写了一个简单的libtool，部分cmake就是这么写的

```bash
find_package(Torch REQUIRED)

if (Torch_FOUND)
    message(STATUS "Torch library found!")
    message(STATUS "include path: ${TORCH_INCLUDE_DIRS}")
    message(STATUS "libraries path: ${TORCH_LIBRARIES}")
else ()
    message(FATAL_ERROR "Could not locate Torch" \n)
endif()

xxxx

target_link_libraries(
    executor
    PUBLIC
    ${TORCH_LIBRARIES}
)
```

然后libtool没问题但是引入到klee中总是链接不到libtorch，我就看打印出的 `${TORCH_LIBRARIES}` 值，感觉有点奇怪 `torch;torch_library;<path2libtorch>/lib/libc10.so`，同时cmake报了警告，我就想来请教下正常引入libtorch是这样的吗？比如上面这个是正确的 `${TORCH_LIBRARIES}` 值吗？

**Comment by AllentDan** [comment]
你用[这个](https://github.com/AllentDan/LibtorchSegmentation/blob/main/CMakeLists.txt)吧，先export下环境变量`Torch_DIR`

**Comment by for-just-we** [comment]
> 你用[这个](https://github.com/AllentDan/LibtorchSegmentation/blob/main/CMakeLists.txt)吧，先export下环境变量`Torch_DIR`

我之前也试过这个，不过是cmake的时候用 `-D` 传的参数，然后最后也是同样的问题

**Comment by AllentDan** [comment]
如果你用-D传的话，就用`set(Torch_DIR "" CACHE STRING "libtorch cmake dir")`， 然后传的时候传libtorch里的cmake的路径

**Comment by for-just-we** [comment]
> 

我先在写的就是 `set(Torch_DIR ${LIB_TORCH_ROOT}/share/cmake/Torch)`，这个 `"libtorch cmake dir"` 是指 `${LIB_TORCH_ROOT}/share/cmake/Torch` 吗？

**Comment by for-just-we** [comment]
> 如果你用-D传的话，就用`set(Torch_DIR "" CACHE STRING "libtorch cmake dir")`， 然后传的时候传libtorch里的cmake的路径

我现在先在写的就是 `set(Torch_DIR ${LIB_TORCH_ROOT}/share/cmake/Torch)`，这个 `"libtorch cmake dir"` 是指 `${LIB_TORCH_ROOT}/share/cmake/Torch` 吗？

**Comment by AllentDan** [comment]
嗯嗯

**Comment by for-just-we** [comment]
> 嗯嗯

那完整的set指令就是 `set(Torch_DIR "" CACHE STRING ${LIB_TORCH_ROOT}/share/cmake/Torch)` 吗?我这么设置的然后就找不到libtorch了

**Comment by AllentDan** [comment]
cmake -D传入

**Comment by AllentDan** [comment]
也就是要么你用`DCMAKE_PREFIX_PATH`传libtorch路径，要么你用`Torch_DIR`表示libtorch下`share/cmake/Torch`。cmake编译需要这个文件夹下的.cmake文件

**Comment by for-just-we** [comment]
> 也就是要么你用`DCMAKE_PREFIX_PATH`传libtorch路径，要么你用`Torch_DIR`表示libtorch下`share/cmake/Torch`。cmake编译需要这个文件夹下的.cmake文件

这个我知道，我现在主要的问题是cmake的时候我感觉`$Torch_Libraries`的值可能不对，我把打印出的这个变量的值放在前面的回答里了，我想问下就是正确的变量值应该是怎样的

**Comment by AllentDan** [comment]
就是那些动态库啊，不过warning我倒是没遇到

**Comment by for-just-we** [comment]
> 就是那些动态库啊，不过warning我倒是没遇到

就是说torch和torch_library其实不应该出现在这个变量的值中，正确变量的值应该是所有.so的路径通过；连接起来的

**Comment by AllentDan** [comment]
这些so文件就在你传的路径里啊....

**Comment by AllentDan** [comment]
这个`${TORCH_LIBRARIES}`就在你传的`Torch_DIR`里的cmake文件里定义了

**Comment by AllentDan** [comment]
你可以打印下`cat /depends/libtorch-cxx11-1.10.2+cu113/share/cmake/Torch/TorchConfig.cmake | grep TORCH_LIBRARIE`

**Comment by for-just-we** [comment]
> 你可以打印下`cat /depends/libtorch-cxx11-1.10.2+cu113/share/cmake/Torch/TorchConfig.cmake | grep TORCH_LIBRARIE`

我刚刚调试了一下，有一个 `$TORCH_LIBRARY` 变量的值是 `<path2libtorch>/lib/libtorch.so`，但是 `$TORCH_LIBRAIES` 的值永远是 `torch;torch_library;<path2libtorch>/lib/libc10.so`，不知道这个值本来就是正确的还是我这cmake解析错误，我看 `TorchConfig.cmake` 最后有一句 `find_package_handle_standard_args(torch DEFAULT_MSG TORCH_LIBRARY TORCH_INCLUDE_DIRS)`，不知道是这一句除了问题还是有什么原因，我方便问下如果在你的环境下打印 `$TORCH_LIBRARIES`，那这个变量值是什么啊？要是我这是错误值的话我直接手动设置这个变量值好了

**Comment by AllentDan** [comment]
除了`<path2libtorch>/lib/libc10.so` 还有这个lib下所有的so文件，以上。

**Comment by AllentDan** [comment]
这个issue我关闭了，因为感觉和项目无关
