### ISSUE TITLE
大佬求联系

### ISSUE THREAD

**Issue by ZZHHogan** [AllentDan/LibtorchTutorials#17]
大佬，看了您写的Libtorch教程，感觉写得很不错，很有帮助。我是知识星球【CV技术指南】的编辑，想问问您能否允许我转载到知识星球中？另外，CV技术指南有上万的计算机视觉相关研究者和从业者，一直在为促进CV行业的发展贡献力量，有很多大佬都在积极参与维护这个社区或组织。目前正在计划对计算机视觉的各种技术做一个完整的技术教程系列，包括CUDA、tensorRT、TVM、openVINO、MNN、openMM、PaddlePaddle、Pytorch源码解读、caffe源码解读、libtorch、Oneflow、Detectron等，计划每个教程由一位大佬来完成，教程将声明作者，以提高您的行业影响力，期望该教程成为大家公认的只要学这个技术就来看这个教程的口碑与影响力，就像视觉SLAM十四讲那样。所以想邀请您为了我们Libtorch的技术教程进行投稿，当然其他教程也可以，我们也可以一起梳理下写的内容一起交流。此外，我们也有一定的稿费。如果您有兴趣的话，可以考虑一下或者了解更详细的情况。

**Comment by AllentDan** [comment]
项目是MIT开源的，可以自由使用的，不过最好可以注明下出处哈

**Comment by ZZHHogan** [comment]
多谢大佬，请问您知乎上关于libtorch的文章也可以转载吗？

**Comment by AllentDan** [comment]
可以转，注明下出处就行

**Comment by ZZHHogan** [comment]
好的，感谢

**Comment by ZZHHogan** [comment]
您好，不知道您这边方便留下联系方式吗？

**Comment by AllentDan** [comment]
微信：may88happy。备注下libtorch
