### ISSUE TITLE
计算bbox的w,h时要不要+1

### ISSUE THREAD

**Issue by ximitiejiang** [AllentDan/LibtorchTutorials#18]
你好，在通过bbox的xmin,ymin,xmax,ymax来计算bbox的w,h时，要不要写成w=xmax-xmin+1, h=ymax-min+1这种方式，比如从像素坐标5到像素坐标10，宽度就应该是10-5+1=6嘛。但确实也看到大量开源框架，包括您这边实现的代码以及数据增强库albumentations里边，也都采用w=xmax-xmin，想知道这是怎么原因？

**Comment by AllentDan** [comment]
这个看框的定义是什么。外包框的话还要减一
