### ISSUE TITLE
 index_put_()

### ISSUE THREAD

**Issue by jerry9055** [AllentDan/LibtorchTutorials#19]
Hi, I am new to libtorch/c++, and I confused when setting values to a torch::Tensor with index_put_()
here is my case
![image](https://user-images.githubusercontent.com/85446108/202890912-45ab55ec-453d-4838-8cc2-3545aa59c858.png)
I fail to set values except for X[0][...]
Would you like to tell me how to set values in Tensor?
Thanks

**Comment by AllentDan** [comment]
The combination of index_put_ and index functions can achieve this task. https://github.com/AllentDan/LibtorchTutorials/tree/main/lesson2-TensorOperations
