### ISSUE TITLE
显存爆了！！！

### ISSUE THREAD

**Issue by zwl995** [AllentDan/LibtorchTutorials#20]
博主，你好，我想请教一下，我使用libtorch cuda版本进行推理时，显存一直在增加直到爆内存，这是什么原因？下面时我调用的方法，，每次来一张图像就会调用这个函数进行推理，模型和数据都放到cuda了，推理完把数据放cpu，使用c10::cuda::CUDACachingAllocator::emptyCache()好像没有用
![image](https://user-images.githubusercontent.com/57057720/224214061-98541dc2-ce77-45a5-a0b2-abc065bb5173.png)

**Comment by AllentDan** [comment]
可能存在的问题哈，你这个函数如果频繁调用的话，会每次将模型从 cpu 到 gpu 再到 cpu，pytorch 模型从 gpu 到cpu 的话，显存好像不会完全释放。
