### ISSUE TITLE
Where did you learn LibTorch

### ISSUE THREAD

**Issue by kevinchahine** [AllentDan/LibtorchTutorials#21]
Where did you learn to code LibTorch in C++? Most resources that I find are only for python. Is there a textbook for C++ LibTorch?

**Comment by AllentDan** [comment]
If you just want to use the api of the libtorch, just configure a environment and use it with header files. For more details, read the source codes.

**Comment by kevinchahine** [comment]
Libtorch works for me. I just want to learn more about it. It looks like you have a very good understanding of it.

**Comment by IncredibleMoney** [comment]
I wonder know how to solve the problem that when building my custom object detection dataset, as there are different numbers of anchor for an image in a batch, the dataloader in libtorch doesn't have a collate_fn function. And I have tried the code in your tutorial. There will be a mistake when iterate the dataloader using  for(const &batch : *dataloader) as it tries to stack the imgs and targets in a batch

**Comment by AllentDan** [comment]
May try https://github.com/AllentDan/LibtorchDetection @IncredibleMoney
