### ISSUE TITLE
qt工程中不能设置 -INCLUDE:?warp_size@cuda@at@@YAHXZ

### ISSUE THREAD

**Issue by be-water-myFriend** [AllentDan/LibtorchTutorials#3]
![image](https://user-images.githubusercontent.com/13702789/114517896-5bc7f280-9c71-11eb-8f3b-0d98a9f87b00.png)

error: LNK2001: 无法解析的外部符号 "int __cdecl at::cuda::warp_size(void)" (?warp_size@cuda@at@@YAHXZ)

**Comment by AllentDan** [comment]
看看这个[链接](https://github.com/pytorch/pytorch/issues/37124)，应该是解决办法

**Comment by be-water-myFriend** [comment]
> 看看这个[链接](https://github.com/pytorch/pytorch/issues/37124)，应该是解决办法

这个链接我试过，其中一点就是要添加 -INCLUDE:?warp_size@cuda@at@@YAHXZ 这个编译参数，但是我这边添加这个参数编译不过;

**Comment by wangj688-lab** [comment]
请问你解决了吗，我也遇到了这个问题，gpu用不了

**Comment by rcg12387** [comment]
@https://github.com/pytorch/pytorch/issues/37124#issuecomment-888830933

> 请问你解决了吗，我也遇到了这个问题，gpu用不了
