### ISSUE TITLE
how to convert trained model in libtorch to onnx? 

### ISSUE THREAD

**Issue by shining-love** [AllentDan/LibtorchTutorials#6]
hello, thanks for your nice repo! I have a question about how to convert trained model in libtorch to onnx? could you give me some instructions?

**Comment by AllentDan** [comment]
This is actually what I want to know. Hope official pytorch supports this feature as soon as possible

**Comment by shining-love** [comment]
> This is actually what I want to know. Hope official pytorch supports this feature as soon as possible

Thanks for your kind reply!I have a idea about convert trained model in libtorch(.pt) to pytorch(.pt)，is it ok？

**Comment by AllentDan** [comment]
I did not find a way for that before, maybe we have to dive into the PyTorch project and find a way work around

**Comment by shining-love** [comment]
> I did not find a way for that before, maybe we have to dive into the PyTorch project and find a way work around

well，thanks for  your great repo so much！I will work on  convert trained model in libtorch(.pt) to pytorch(.pt).
