### ISSUE TITLE
LibTorch使用cuda的问题

### ISSUE THREAD

**Issue by wang8713** [AllentDan/LibtorchTutorials#9]
你好，我刚刚接触libtorch但在使用的过程中出现了问题。我使用gpu的时候在运行 "module.to(device_type);" 时出现了不动的问题。
情况如下图。在运行到81行给模型加载到gpu时出现了下面这种情况。
![Snipaste_2021-12-27_17-12-08](https://user-images.githubusercontent.com/90226334/147455927-3e99dece-c883-4d4f-b6af-ddf26adac2e3.png)
在使用cpu时一切正常。
我的环境是 cuda10.2、cudnn(8.3.1 / 7.6.5)这两个版本都试过、libtorch1.8.0-release、VS2019、pytorch1.8.0。

**Comment by AllentDan** [comment]
点击[这里](https://allentdan.github.io/2020/12/16/pytorch%E9%83%A8%E7%BD%B2torchscript%E7%AF%87/#more)的一些报错部分

**Comment by wang8713** [comment]
好的，谢谢您回复，我已经解决了。
